### ISSUE TITLE
Edge is not rending same as previous version

### ISSUE THREAD

**Issue by wanglongqi** [scls19fr/windrose#52] opened 2017-04-10 06:53 UTC
Here is the previous version (get from readme):

![](https://github.com/scls19fr/windrose/raw/master/screenshots/bar.png)

Here is the new version (get from https://nbviewer.jupyter.org/github/scls19fr/windrose/blob/master/windrose_sample_random.ipynb):

![image](https://cloud.githubusercontent.com/assets/6874783/24849214/3e3d2074-1dfd-11e7-84af-54fe46d84841.png)

It looks like the readme version has a round edge, but the ipynb version has a straight edge. How can I get the old version with that round edge?

**Comment by scls19fr** [comment] 2017-04-10 07:50
Closing as duplicate of https://github.com/scls19fr/windrose/issues/43

**Closed by scls19fr** 2017-04-10 07:50 UTC
